### ISSUE TITLE
Image enlarging issue on visions page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Jacinthe-Internal-S.O.---May-11#1]
Bug - image enlarging and blur on visions page - https://7csc7j8b85ome1fh-2379350067.shopifypreview.com/pages/vision 
Exp - Image should not get enlarge and blur.
Ref Link - 
- https://drive.google.com/file/d/149L13YK6vBtYdz2vw2_Gl_KbW7hsdmrO/view
- https://drive.google.com/file/d/1Z_1j4z0Hlx6T5-btus9WAsp8aa4hC6Be/view

**Comment by devabulabbas** [comment]
@ankitcedcoss Resolved

**Comment by Shoaibans** [comment]
Fixed.

**Comment by ankitcedcoss** [comment]
Bug Fixed
